# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(6a012649-9e7f-4cec-b5d7-d4adee64fbbf)'
    imageToDeploy: 'acrapl2003faj13mar.azurecr.io/aspnetcorecontainer:latest'
    containerAppName: 'aca-apl2003'
    resourceGroup: 'RG1'